// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.0
// source: ray_tracer.proto

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorldDataService_RegisterClient_FullMethodName = "/ray_tracer.worldDataService/RegisterClient"
)

// WorldDataServiceClient is the client API for WorldDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorldDataServiceClient interface {
	RegisterClient(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorldData], error)
}

type worldDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorldDataServiceClient(cc grpc.ClientConnInterface) WorldDataServiceClient {
	return &worldDataServiceClient{cc}
}

func (c *worldDataServiceClient) RegisterClient(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorldData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorldDataService_ServiceDesc.Streams[0], WorldDataService_RegisterClient_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientInfo, WorldData]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorldDataService_RegisterClientClient = grpc.ServerStreamingClient[WorldData]

// WorldDataServiceServer is the server API for WorldDataService service.
// All implementations must embed UnimplementedWorldDataServiceServer
// for forward compatibility.
type WorldDataServiceServer interface {
	RegisterClient(*ClientInfo, grpc.ServerStreamingServer[WorldData]) error
	mustEmbedUnimplementedWorldDataServiceServer()
}

// UnimplementedWorldDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorldDataServiceServer struct{}

func (UnimplementedWorldDataServiceServer) RegisterClient(*ClientInfo, grpc.ServerStreamingServer[WorldData]) error {
	return status.Errorf(codes.Unimplemented, "method RegisterClient not implemented")
}
func (UnimplementedWorldDataServiceServer) mustEmbedUnimplementedWorldDataServiceServer() {}
func (UnimplementedWorldDataServiceServer) testEmbeddedByValue()                          {}

// UnsafeWorldDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorldDataServiceServer will
// result in compilation errors.
type UnsafeWorldDataServiceServer interface {
	mustEmbedUnimplementedWorldDataServiceServer()
}

func RegisterWorldDataServiceServer(s grpc.ServiceRegistrar, srv WorldDataServiceServer) {
	// If the following call pancis, it indicates UnimplementedWorldDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorldDataService_ServiceDesc, srv)
}

func _WorldDataService_RegisterClient_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorldDataServiceServer).RegisterClient(m, &grpc.GenericServerStream[ClientInfo, WorldData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorldDataService_RegisterClientServer = grpc.ServerStreamingServer[WorldData]

// WorldDataService_ServiceDesc is the grpc.ServiceDesc for WorldDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorldDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ray_tracer.worldDataService",
	HandlerType: (*WorldDataServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterClient",
			Handler:       _WorldDataService_RegisterClient_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ray_tracer.proto",
}
